#############
# Applications of predicted lifetime values #
#############

#####
# Step 1 : Data setup #
#####

#Load library and data
library(lubridate)
library(BTYDplus)
library(BTYD)
library(plyr)
library(reshape2)
library(ggplot2)
library(dplyr)

data <- read.table('CDNOW_master.txt', sep = "", header=FALSE, na.strings = "", stringsAsFactors = FALSE)
data_tbl <- dplyr::as_tibble(data) %>%
  dplyr::rename(cust = V1) %>%
  dplyr::mutate(date = as.Date(as.character(V2), format = '%Y%m%d')) %>%
  dplyr::select(-V2) %>%
  dplyr::rename(orders = V3) %>%
  dplyr::rename(sales = V4) %>%
  dplyr::glimpse()

#Re-transform tibble back to data.frame as BTYDplus package runs better with this format
data_df <- as.data.frame(data_tbl)

######
# Step 2 : Predict CLV using BTYD's Beta Geometric / Negative Binomial distribution model (BG/NBD) #
######

customer_rdf <- BTYDplus::elog2cbs(data_df,
                                   unit = 'days',
                                   T.cal = as.Date('1998-03-24'),
                                   T.tot = max(data_df$date))
#Set prediction horizon to 1 year for all customers but this could change
customer_rdf$sales_avg = customer_rdf$sales / (customer_rdf$x + 1)

bgnbd_rdf <- customer_rdf
bgnbd_rdf$T.star <- 365 #T.star is the 365 day prediction horizon (same for all customers)

#Use Beta-Geometric Negative Binomial Distribution Model (BGNBD) to predict
params_bgnbd <- BTYD::bgnbd.EstimateParameters(bgnbd_rdf)
bgnbd_rdf$predicted_bgnbd <- BTYD::bgnbd.ConditionalExpectedTransactions(params = params_bgnbd,
                                                                         T.star = bgnbd_rdf$T.star,
                                                                         x = bgnbd_rdf$x,
                                                                         t.x = bgnbd_rdf$t.x,
                                                                         T.cal = bgnbd_rdf$T.cal)
#Calculate CLV by multiplying the predicted number of transactions by the average monetary value spend
bgnbd_rdf$predicted_clv <- bgnbd_rdf$sales_avg * bgnbd_rdf$predicted_bgnbd
#This multiplies the predicted_bgnbd number of predicted transaction counts by the average spend a customer will have

#Get Palive after calibration period
bgnbd_rdf$palive <- BTYD::bgnbd.PAlive(params_bgnbd, x=bgnbd_rdf$x, t.x=bgnbd_rdf$t.x, T.cal=bgnbd_rdf$T.cal)


#Visualize the CLV results
hist(bgnbd_rdf$predicted_clv, xlim = c(0,500), breaks = 3000)
plot(density(bgnbd_rdf$predicted_clv), xlim = c(0,300))

#Get final output customers table
head(bgnbd_rdf)

######
# Step 3 : Analyses using the above predicted 1-year CLV #
######

### Step 3-1 : Build Simple Topline metrics
# Get customer cohorts by year
cust_cohorts <- data_tbl %>%
  dplyr::group_by(cust) %>%
  dplyr::summarise(join_date = min(date)) %>%
  dplyr::mutate(cohort_year = lubridate::year(join_date)) %>%
  dplyr::select(-join_date) %>%
  dplyr::glimpse()

# Get customer sales by year (cohorts)
cust_sales_cohorts <- data_tbl %>%
  #dplyr::left_join(cust_cohorts, by = c("cust" = "cust")) %>%
  dplyr::mutate(sales_year = lubridate::year(date)) %>%
  dplyr::group_by(cust, sales_year) %>%
  dplyr::summarise(total_sales_year = sum(sales)) %>%
  dplyr::left_join(cust_cohorts, by = c("cust" = "cust")) %>%
  dplyr::glimpse()

# Get customer cohorts by year-month
cust_cohorts2 <- data_tbl %>%
  dplyr::group_by(cust) %>%
  dplyr::summarise(join_date = min(date)) %>%
  dplyr::mutate(cohort_year_month = paste0(lubridate::year(join_date), "-", lubridate::month(join_date))) %>%
  dplyr::select(-join_date) %>%
  dplyr::glimpse()

# Get customr sales by year-month (cohorts)
cust_sales_cohorts2 <- data_tbl %>%
  dplyr::mutate(sales_year_month = paste0(lubridate::year(date), "-", lubridate::month(date))) %>%
  dplyr::group_by(cust, sales_year_month) %>%
  dplyr::summarise(total_sales_year_month = sum(sales)) %>%
  dplyr::left_join(cust_cohorts2, by = c("cust" = "cust")) %>%
  dplyr::glimpse()

# Display top line metrics by cohorts by year - doesn't really have too much meaning due to the small amount of data
ggplot2::ggplot(cust_sales_cohorts, ggplot2::aes(fill = cohort_year, y = total_sales_year, x = sales_year)) +
  ggplot2::geom_bar(position = 'stack', stat = 'identity') +
  ggplot2::ggtitle('Sales Generated by Cohorts in each Year') +
  ggplot2::xlab('Year') +
  ggplot2::ylab('Sales') +
  ggplot2::theme_minimal()

# Display top line metrics by cohorts by year_month - shows a bit more details but only has 3 cohorts b/c all customers joined in these 3 months
ggplot2::ggplot(cust_sales_cohorts2, ggplot2::aes(fill = cohort_year_month, y = total_sales_year_month, x = sales_year_month)) +
  ggplot2::geom_bar(position = 'stack', stat = 'identity') +
  ggplot2::ggtitle('Sales Generated by Cohorts in each Year/Month') +
  ggplot2::xlab('Year') +
  ggplot2::ylab('Sales') +
  ggplot2::theme_minimal()

# Get similar chart for customer acquisition by years and year_months
cust_count_cohorts <- data_tbl %>%
  dplyr::group_by(cust) %>%
  dplyr::summarise(join_date = min(date)) %>%
  dplyr::mutate(acq_year_month = paste0(lubridate::year(join_date), "-", lubridate::month(join_date))) %>%
  dplyr::select(-join_date) %>%
  dplyr::group_by(acq_year_month) %>%
  dplyr::summarise(total_cust = dplyr::n()) %>%
  dplyr::arrange(acq_year_month) %>%
  dplyr::glimpse()

ggplot2::ggplot(cust_count_cohorts, ggplot2::aes(y = total_cust, x = acq_year_month)) +
  ggplot2::geom_bar(position='dodge', stat = 'identity') +
  ggplot2::ggtitle('Customers Acquired by Year/Month') +
  ggplot2::xlab('Acquired Year-Month') +
  ggplot2::ylab('Number of Customers') +
  ggplot2::theme_minimal()

### Actions that can be taken based on this insight:
# i) Easier to understand which cohorts are driving the yearly revenue
# ii) Indirectly see how some cohorts are retained more than other cohorts to contribute to the followign years' revenue
# iii) Visuals can be used as top line metrics that would be general enough to report/share with other non-technical people.

### Step 3-2 : Segment Customers by High and Low CLV
# Label customers with top 80th percentile of CLV as 'High CLV' and 'Low CLV' for others
# Label customers with Probability of being alive as of today (palive) as 'Active' if higher than 0.8
clv_labels <- bgnbd_rdf %>% 
  dplyr::arrange(predicted_clv) %>%
  dplyr::mutate(temp_label = 1) %>%
  dplyr::mutate(cumpct = 100*cumsum(temp_label) / sum(temp_label)) %>%
  dplyr::select(-temp_label) %>%
  dplyr::mutate(clv_segment = dplyr::if_else(cumpct < 0.7, 'Low CLV', 'High CLV')) %>%
  dplyr::mutate(palive_segment = dplyr::if_else(palive < 0.8, 'Not Active', 'Active')) %>%
  dplyr::mutate(cust_segment = paste0(palive_segment, ' ', clv_segment)) %>%
  dplyr::select(-clv_segment, -palive_segment) %>%
  dplyr::glimpse()

clv_labels_summary <- clv_labels %>%
  dplyr::group_by(cust_segment) %>%
  dplyr::summarise(cust_count = n_distinct(cust)) %>%
  dplyr::glimpse()

# Visualize customer segments
ggplot2::ggplot(clv_labels_summary, ggplot2::aes(fill = cust_segment, y = cust_count, x = cust_segment)) +
  ggplot2::geom_bar(position='dodge', stat='identity') +
  ggplot2::ggtitle('Customer Segments by High/Low CLV and Prob. of being Alive') +
  ggplot2::xlab('Customer Segments') +
  ggplot2::ylab('Customer Counts')

### Actions that can be taken based on this insights:
#i) Using the segmented customers, we can target X% of the customer base for up sells or retention campaigns based on their probability of being an active customer and how much they would be worth in 1-year since they were acquired.
#ii) Identify at the customer level who these customers are (and who are not these customers) instead of relying on an aggregated cohort analysis.

### Step 3-3 : Determine which customer is profitable in respect to costs
# Let's assume it costs $100 to acquire a customer (i.e.: blended acquisition cost)
# Identify which customer is profitable from a lifetime value perspective assuming a 100% profit rate (i.e.: revenue = profits)

# Get total profitable customers 
cust_profits <- bgnbd_rdf %>%
  dplyr::mutate(cac = 100.0) %>%
  dplyr::mutate(net_profit = predicted_clv - cac) %>%
  dplyr::arrange(net_profit) %>%
  dplyr::mutate(temp_label = 1) %>%
  dplyr::mutate(cumpct = 100*cumsum(temp_label) / sum(temp_label)) %>%
  dplyr::select(-temp_label) %>%
  dplyr::mutate(profitable = dplyr::if_else(net_profit < 0, 'Unprofitable', 'Profitable')) %>%
  dplyr::mutate(net_profit = abs(net_profit)) %>%
  dplyr::mutate(row_no = dplyr::row_number()) %>%
  dplyr::glimpse()

ggplot2::ggplot(cust_profits, ggplot2::aes(fill = profitable, x = profitable, y = net_profit)) +
  ggplot2::geom_bar(position = 'dodge', stat='identity') +
  ggplot2::ggtitle('Profitability from CLV Perspective') +
  ggplot2::xlab('Profitable Customers') +
  ggplot2::ylab('Net Profit') +
  ggplot2::theme_minimal()

# Get total profitable customers by cohorts
cohorts_year_month <- data_tbl %>%
  dplyr::group_by(cust) %>%
  dplyr::summarise(join_date = min(date)) %>%
  dplyr::mutate(join_year_month = paste0(lubridate::year(join_date), '-', lubridate::month(join_date))) %>%
  dplyr::select(-join_date) %>%
  dplyr::glimpse()

cust_profits_by_cohorts <- bgnbd_rdf %>%
  dplyr::left_join(cohorts_year_month, by = c("cust" = "cust")) %>%
  dplyr::mutate(cac = 100.0) %>%
  dplyr::mutate(net_profit = predicted_clv - cac) %>%
  dplyr::arrange(net_profit) %>%
  dplyr::mutate(temp_label = 1) %>%
  dplyr::mutate(cumpct = 100*cumsum(temp_label) / sum(temp_label)) %>%
  dplyr::select(-temp_label) %>%
  dplyr::mutate(profitable = dplyr::if_else(net_profit < 0, 'Unprofitable', 'Profitable')) %>%
  dplyr::mutate(net_profit = abs(net_profit)) %>%
  dplyr::mutate(row_no = dplyr::row_number()) %>%
  dplyr::glimpse()

ggplot2::ggplot(cust_profits_by_cohorts, ggplot2::aes(fill = join_year_month, x = profitable, y = net_profit)) +
  ggplot2::geom_bar(position = 'dodge', stat='identity') +
  ggplot2::ggtitle('Profitability by Cohorts from CLV Perspective') +
  ggplot2::xlab('Cohorts') +
  ggplot2::ylab('Net Profit') +
  ggplot2::theme_minimal()

### Actions that can be taken based on this insight: 
#i) Number of profitable customers acquired is decreasing and should be investigated into any changes in acquisition campaigns, product launches/changes, etc.
#ii) Number of unprofitable customers remain consistent and small. These customers should be left out from campaigns (e.g.: product up sells, etc.) since they won't be profitable.